-- MySQL Script generated by MySQL Workbench
-- Wed Nov  4 17:17:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` DEFAULT CHARACTER SET utf8 ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`clientes` (
  `CPF` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `dtNasc` DATETIME NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`jogos` (
  `codigoJogo` INT NOT NULL,
  `nomeJogo` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `plataforma` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `imgJogo` BLOB(100) NOT NULL,
  PRIMARY KEY (`codigoJogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja`.`compra` (
  `codigoCompra` INT NOT NULL AUTO_INCREMENT,
  `dtCompra` DATETIME NOT NULL,
  `sts_compra` VARCHAR(10) NOT NULL,
  `clientes_CPF` INT NOT NULL,
  `jogos_codigoJogo` INT NOT NULL,
  PRIMARY KEY (`codigoCompra`),
  INDEX `fk_compra_clientes_idx` (`clientes_CPF` ASC) VISIBLE,
  INDEX `fk_compra_jogos1_idx` (`jogos_codigoJogo` ASC) VISIBLE,
  CONSTRAINT `fk_compra_clientes`
    FOREIGN KEY (`clientes_CPF`)
    REFERENCES `loja`.`clientes` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_jogos1`
    FOREIGN KEY (`jogos_codigoJogo`)
    REFERENCES `loja`.`jogos` (`codigoJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
